window.galleryPhotos = [
  // המקום והנוף
  { file: "ein-yahav-aerial.webp", caption: "צילום אוויר – מושב עין יהב והחממות" },
  { file: "eternal-summer-sign.webp", caption: "השלט בכניסה למושב – ארץ הקיץ הנצחית" },
  { file: "moshav-historic.webp", caption: "המושב בראשית ימיו – תמונה היסטורית" },
  { file: "shai-historic-kitchen.webp", caption: "שי בן אליהו במטבח הצריף – ימי הראשית" },
  { file: "beit-haam-cornerstone.webp", caption: "הנחת אבן הפינה לבית העם בעין יהב" },
  { file: "historic-2.webp", caption: "השלט בכניסה לארץ הקיץ הנצחית" },
  { file: "vegetable-hanukkiah.webp", caption: "חנוכייה מירקות הערבה" },

  // עבודה וחיים בערבה
  { file: "shai-hagi-sifting.webp", caption: "שי וחגי מנערים בצלצל – עבודת המושב" },
  { file: "shai-mara-canola-field.webp", caption: "שי ומרה בשדה הקינואה" },
  { file: "shai-speaking.webp", caption: "שי נואם" },
  { file: "shai-marzeva-hike.webp", caption: "שי מטייל במרזבה" },
  { file: "sleeping-on-the-road.webp", caption: "ישן על הכביש" },
  { file: "shai-melons.webp", caption: "שי במלונים" },
  { file: "shai-greenhouse-1999.webp", caption: "שי בחממה, 1999" },
  { file: "shai-jubilee-opening-1.webp", caption: "שי בפתיחת אירועי היובל" },
  { file: "shai-jubilee-opening-2.webp", caption: "שי בפתיחת אירועי היובל" },
  { file: "airport-opening.webp", caption: "פתיחת שדה התעופה" },
  { file: "onion-loading.webp", caption: "העמסת בצל לאחר הקינוב" },
  { file: "shai-dudu-greenhouse.webp", caption: "שי ודודו מנקים חממה" },
  { file: "shai-mara-canola-2.webp", caption: "שי ומרה בשדה הקינואה" },
  { file: "shai-desert-bloom.webp", caption: "שי בפריחה מדברית" },
  { file: "hitnahalut-1968.webp", caption: "חג ההתנחלות, פברואר 1968" },
  { file: "permanent-settlement-ceremony.webp", caption: "ההורים בטקס העלייה ליישוב הקבע" },
  { file: "new-school-ceremony.webp", caption: "טקס המעבר לבית הספר החדש" },
  { file: "first-grade-shitim.webp", caption: "עלייה לכיתה א' עם המעבר לבית הספר החדש \"שיטים\"" },
  { file: "recorder-group.webp", caption: "קבוצת חליליות בניצוח מלכה הלל" },
  { file: "parade-float-1986.webp", caption: "עגלת המצעד, 1986" },
  { file: "parents-vegetable-garden.webp", caption: "ההורים ליד הצינור המפורסם בגן הירק" },
  { file: "dudu-ziv-sara-flood.webp", caption: "דודו, זיו ושרה ליד האוטו בשיטפון" },

  // מפגשים היסטוריים
  { file: "shai-ben-gurion-izruah.webp", caption: "שי עם דוד בן גוריון בחג האזרוח בעמק הנעלם" },
  { file: "shai-golda-meir.webp", caption: "שי וגולדה מאיר" },
  { file: "shai-golda-meir-2.webp", caption: "שי עם גולדה מאיר – תמונה היסטורית" },
  { file: "shai-rabin.webp", caption: "שי בן אליהו עם ראש הממשלה יצחק רבין" },
  { file: "shai-rabin-tzur-1993.webp", caption: "שי עם רה\"מ יצחק רבין ושר החקלאות יעקב צור, 11.3.1993" },
  { file: "shai-king-abdullah.webp", v: 2, caption: "שי בן אליהו עם המלך עבדאללה השני" },
  { file: "shai-hillary-abdullah-rania.webp", caption: "שי בן אליהו עם הילרי קלינטון, המלך עבדאללה והמלכה רניה" },
  { file: "family-shimon-peres.webp", caption: "בני המשפחה עם הנשיא שמעון פרס בבית הנשיא" },
  { file: "with-david-shatner.webp", caption: "עם דוד שטנר" },
  { file: "shai-ben-gurion-1970.webp", caption: "שי עם דוד בן גוריון, 26.6.1970" },
  { file: "shai-assaf-hefetz.webp", caption: "שי בביקור אסף חפץ" },
  { file: "btr-event-1.webp", caption: "מתוך אירועי פרויקט BTR" },
  { file: "btr-event-2.webp", caption: "טקס פרויקט BTR" },
  { file: "btr-event-3.webp", caption: "מתוך אירועי פרויקט BTR" },
  { file: "sharon-btr-donors.webp", caption: "שרון ותורמי ה-BTR" },
  { file: "before-jordan-flight.webp", caption: "לפני הטיסה לירדן" },
  { file: "ruti-shai-jordan.webp", caption: "רותי ושי בירדן" },
  { file: "shai-jordan-1996.webp", caption: "שי בירדן, 1996" },
  { file: "elyakim-rubinstein.webp", caption: "השופט אליקים רובינשטיין" },

  // השיטפונות בערבה
  { file: "arava-stream-flood.webp", caption: "שיטפון בנחל ערבה – אדם במים השוצפים" },
  { file: "flood-1.webp", caption: "רכב שנתקע בבוץ לאחר שיטפון" },
  { file: "flood-2.webp", caption: "חילוץ רכב מהבוץ באמצעות טרקטור" },
  { file: "flood-3.webp", caption: "חילוץ רכב לאחר השיטפון" },

  // משפחה וזיכרון
  { file: "meirka-shulamit-wedding.webp", caption: "חתונת מאירקה ושלומית" },
  { file: "shulamit-meirka-portrait.webp", caption: "שלומית ומאירקה" },
  { file: "meirka-moshav-event.webp", caption: "מאירקה באירוע במושב" },
  { file: "shai-hagi-ziv-wedding.webp", caption: "שי וחגי בחתונת זיו" },
  { file: "dudu-ben-eliyahu.webp", caption: "דודו בן אליהו" },
  { file: "hadas-ben-eliyahu.webp", caption: "הדס בן אליהו" },
  { file: "omri-concert-2009.webp", caption: "בקונצרט של עמרי, יולי 2009" },
  { file: "utopia-12-2009.webp", caption: "בפארק אוטופיה, דצמבר 2009" },
  { file: "utopia-2009.webp", caption: "בפארק אוטופיה, 2009" },
  { file: "ein-hod.webp", caption: "בעין הוד" },
  { file: "ashdod-2001.webp", caption: "באשדוד, 2001" },
  { file: "shai-hershey-1986.webp", caption: "שי בהרשי, 1986" },
  { file: "shai-dining-table.webp", caption: "שי בשולחן האוכל" },
  { file: "shai-ruti-rotem-class-trip.webp", caption: "שי ורותי בדרך לפעילות כיתתית של רתם" },
  { file: "shai-yuval-ruti-rotem-dudu.webp", caption: "שי, יובל, רותי, רתם ודודו" },
  { file: "shai-hadas-omri.webp", caption: "שי, הדס ועמרי" },
  { file: "family-peach-orchard.webp", caption: "תמונה משפחתית במטע האפרסקים" },
  { file: "sara-dudu-hadas-gila-1969.webp", caption: "שרה, דודו, הדס וגילה, 1969" },
  { file: "shai-portrait.webp", caption: "שי בן אליהו" },
  { file: "shai-75th-birthday.webp", caption: "יום הולדת 75 לשי, 1.3.2010" },
  { file: "shai-ruti-grandchildren.webp", caption: "שי ורותי עם הנכדים בעין יהב" },
  { file: "shai-ofer.webp", caption: "שי ועופר" },
  { file: "shai-shlomo.webp", caption: "שי ושלמה" },
  { file: "shai-shahar-birthday-2008.webp", caption: "שי ביום ההולדת של שחר, אוקטובר 2008" },
  { file: "sara-baby-shai.webp", caption: "שרה עם שי התינוק" },
  { file: "ruti-naava-babies.webp", caption: "רותי ואחותה התאומה נאוה, תינוקות" },
  { file: "ruti-naava.webp", caption: "רותי ונאוה" },
  { file: "saba-alyusha-1986.webp", caption: "סבא אליושה, 1986" },
  { file: "shai-doda-genia.webp", caption: "שי ודודה ג'ניה" },
  { file: "with-zeide.webp", caption: "עם זיידה" },
  { file: "shai-zeide-2000.webp", caption: "שי וזיידה בהנחת אבן הפינה לגנים החדשים, נובמבר 2000" },
  { file: "ruti-shai-lea-wedding.webp", caption: "רותי, שי ולאה בחתונה" },
  { file: "ruti-shai-botanic-1986.webp", caption: "רותי ושי בגן הבוטני, 1986" },
  { file: "ruti-shai-1995.webp", caption: "רותי ושי, 1995" },
  { file: "shai-ruti-sugarloaf.webp", caption: "שי ורותי בהר הסוכר" },
  { file: "shai-ruti-bench.webp", caption: "שי ורותי על ספסל בגן" },
  { file: "shai-loving-hug.webp", caption: "חיבוק אוהב" },
  { file: "shai-street.webp", caption: "שי בן אליהו" },
  { file: "shai-portrait-3.webp", caption: "שי בן אליהו" },
  { file: "shai-dudu-hadas-bikes.webp", caption: "שי, דודו והדס על אופניים" },
  { file: "shai-hadas-dudu-michal.webp", caption: "שי, הדס, דודו ומיכל" },
  { file: "shai-ruti-omri-baby.webp", caption: "שי ורותי עם עמרי התינוק" },
  { file: "shai-ruti-yuval-tal.webp", caption: "שי, רותי, יובל וטל" },
  { file: "shai-omri.webp", caption: "שי ועמרי" },
  { file: "shai-yotam.webp", caption: "שי ויותם" },
  { file: "yotam.webp", caption: "יותם" },
  { file: "ofer-baby-sleeping.webp", caption: "עופר תינוק ישן" },
  { file: "shai-rotem-borot-lutz.webp", caption: "שי ורתם בבורות לוץ" },
  { file: "hadas-army.webp", caption: "הדס בטירונות" },
  { file: "rotem-wedding-1.webp", caption: "חתונתם של רתם וקובי" },
  { file: "rotem-wedding-2.webp", caption: "חתונתם של רתם וקובי" },
  { file: "family-jubilee.webp", caption: "כל המשפחה בחג היובל" },
  { file: "tu-bishvat-family.webp", caption: "ט\"ו בשבט משפחתי" },
  { file: "shai-70th-neve-tzedek.webp", caption: "יום הולדת 70 בנווה צדק" },
  { file: "four-musketeers.webp", caption: "ארבעת המוסקטרים" },
  { file: "vegetable-hanukkiah-2.webp", caption: "חנוכייה מירקות הערבה" },
  { file: "halloween-1986.webp", caption: "האלווין, 1986" },
  { file: "chinese-restaurant-ny.webp", caption: "במסעדה הסינית בניו יורק" },
  { file: "homeless-ny.webp", caption: "ההומלס בניו יורק" },
  { file: "williamsburg-1987.webp", caption: "וויליאמסבורג, וירג'יניה 1987" },
  { file: "longwood-park-1987.webp", caption: "פארק לונגווד, 1987" },
  { file: "june-1986.webp", caption: "יוני 1986" },
  { file: "saba-shai-2008.webp", caption: "סבא שי, אפריל 2008" },
  { file: "family-album-2001.webp", caption: "מתוך האלבום המשפחתי, 2001" },
  { file: "dudu-portrait.webp", caption: "דודו בן אליהו" },
  { file: "ruti-hadas-rotem-usa.webp", caption: "רותי, הדס ורתם בארצות הברית" },
  { file: "family-trip.webp", caption: "בטיול משפחתי" },
  { file: "family-album-5.webp", caption: "מתוך האלבום המשפחתי" },
  { file: "family-album-7.webp", caption: "מתוך האלבום המשפחתי" },
  { file: "shai-1970.webp", caption: "שי, 1970" },
  { file: "vancouver-1988.webp", caption: "בוונקובר, 1988" },
  { file: "shai-2003.webp", caption: "שי, 2003" },
  { file: "shai-2004.webp", caption: "שי, 2004" },
  { file: "historic-1.webp", caption: "טקס זיכרון משפחתי" },
  { file: "historic-3.webp", caption: "כינוס משפחתי באתר הזיכרון" },

  // שי וחגי
  { file: "shai-hagi-living-room.webp", caption: "שי וחגי בסלון הבית" },
  { file: "shai-hagi-flowers.webp", caption: "שי וחגי – רגע משותף" },
  { file: "shai-hagi-gvati.webp", caption: "שי, חגי וגבתי" },
  { file: "cheche-hagi.webp", caption: "צ'צ'ה וחגי" },

  // הולנד
  { file: "holland-tulip-field-2006.webp", caption: "שי מצלם את רותי בשדה הצבעונים – ומצלמים אותו מצלם אותה" },
  { file: "shai-michael-orhella-holland-tulips.webp", caption: "שי, מייקל ואורהלה בגן הצבעונים בהולנד" },
  { file: "amnon-orhella-michael-shai-holland.webp", caption: "אמנון, אורהלה, מייקל ושי בהולנד" },
  { file: "shai-michael-orhella-holland-2.webp", caption: "שי, מייקל ואורהלה בהולנד" },
  { file: "holland-sheva.webp", caption: "עם שבע בהולנד" },
  { file: "holland-group-michael.webp", caption: "אמנון, אורלה, שבע, רותי ושי – מייקל מצלם" },
  { file: "orhella-shai-holland.webp", caption: "אורהלה ושי בהולנד" },
  { file: "holland-2006-1.webp", caption: "סיור בהולנד" },
  { file: "holland-tour-2006.webp", caption: "סיור בהולנד" },
];
