// השירים המקוריים בכתב ידו של שי – סריקות.
// להוספה: העלו קובץ ל-images/songs/ והוסיפו שורה כאן. v: מספר גרסה – העלו אותו אם החלפתם קובץ קיים באותו שם.
window.shaiSongs = [
  { file: "orla-50.webp", caption: "אורלה בת 50" },
  { file: "orla-60.webp", caption: "אורלה בת 60" },
  { file: "al-tachshevu-1968.webp", caption: "\"אל תחשבו שאיננו יודעים\", 1968" },
  { file: "amnon-navon-60.webp", caption: "אמנון נבון בן 60" },
  { file: "razi-uri-bar-mitzvah.webp", caption: "לבר המצווה של רזי עורי" },
  { file: "bereshit.webp", caption: "\"בראשית\"" },
  { file: "parents-25th.webp", caption: "ברכה להורינו – חג ה־25" },
  { file: "hanukkah-blessing-rotem.webp", caption: "ברכה לחנוכה – נכתב עבור רתם למסיבת חנוכה בבית הספר" },
  { file: "rosh-hashanah-blessing.webp", caption: "ברכה לראש השנה" },
  { file: "dudu-40.webp", caption: "דודו בן 40, 11.2.2002" },
  { file: "dudu-25.webp", caption: "דודו בן 25" },
  { file: "ayelet-schlecht-birth.webp", caption: "ה־63 – להולדת איילת שלכט" },
  { file: "haba-koach-1.webp", caption: "\"הבא כוח\" – חלק א', 1967" },
  { file: "haba-koach-2.webp", caption: "\"הבא כוח\" – חלק ב'" },
  { file: "haba-koach-3.webp", caption: "\"הבא כוח\" – חלק ג'" },
  { file: "haba-koach-4.webp", caption: "\"הבא כוח\" – חלק ד'" },
  { file: "hadas-dudu-yuval-tal-2000.webp", caption: "להדס ודודו להולדת יובל וטל, 2000" },
  { file: "hadas-dudu-michal-1998.webp", caption: "להדס ודודו להולדת מיכל, 1998" },
  { file: "hadas-graduation-1.webp", caption: "הדס מסיימת י\"ב – חלק א'" },
  { file: "hadas-graduation-2.webp", caption: "הדס מסיימת י\"ב – חלק ב'" },
  { file: "hadas-graduation.webp", caption: "הדס מסיימת י\"ב" },
  { file: "ein-yahav-10th-invitation.webp", caption: "הזמנה לחג העשור לעין יהב" },
  { file: "great-flood-1.webp", caption: "\"השיטפון הגדול\" – חלק א'" },
  { file: "great-flood-2.webp", caption: "\"השיטפון הגדול\" – חלק ב'" },
  { file: "hatchala-1967.webp", caption: "\"התחלה\", 1967" },
  { file: "ziv-porat-wedding-1991.webp", caption: "לזיו פורת ליום חתונתה, 1991" },
  { file: "first-graduates-1980.webp", caption: "חג הבוגרים הראשון – הכיתה של דודו, 1980" },
  { file: "hagi-53.webp", caption: "חגי בן 53" },
  { file: "haim-1977.webp", caption: "\"חיים\", 1977" },
  { file: "hanukkah-1990.webp", caption: "חנוכה, 1990" },
  { file: "hanukkah-1993.webp", caption: "חנוכה, 1993" },
  { file: "hanukkah.webp", caption: "חנוכה" },
  { file: "telephone-song-draft.webp", caption: "טיוטת \"שיר הטלפון\"" },
  { file: "memorial-day.webp", caption: "יום הזיכרון ופתיח לשיר אבל" },
  { file: "childrens-day-1981.webp", caption: "יום הילד, 1981" },
  { file: "independence-day-1998.webp", caption: "יום העצמאות, 1998" },
  { file: "independence-day-1999.webp", caption: "יום העצמאות, 1999" },
  { file: "independence-day-1989.webp", caption: "יום העצמאות, 1989" },
  { file: "yotam-first-grade-2000.webp", caption: "יותם עולה לכיתה א', 2000" },
  { file: "carmit-40.webp", caption: "כרמית בת 40" },
  { file: "dagan-bar-lavan-1991.webp", caption: "לדגן בר־לבן, נובמבר 1991" },
  { file: "ofer-birth-manuscript.webp", caption: "להולדת עופר – כתב יד" },
  { file: "hagi-farewell.webp", caption: "לחגי בלכתו" },
  { file: "moti-40.webp", caption: "מוטי בן 40" },
  { file: "machar-1967.webp", caption: "\"מחר\", 1967" },
  { file: "michael-50.webp", caption: "מייקל בן 50" },
  { file: "mara-70.webp", caption: "מרה בן 70" },
  { file: "nizkor-2.webp", caption: "\"נזכור\" – גרסה שנייה" },
  { file: "new-york-ending.webp", caption: "\"ניו יורק\" – סיום" },
  { file: "new-york.webp", caption: "\"ניו יורק\"" },
  { file: "naalei-habait.webp", caption: "\"נעלי הבית\"" },
  { file: "naomi-zoller-50.webp", caption: "נעמי זולר בת 50" },
  { file: "savta-90-1.webp", caption: "סבתא בת 90 – חלק א'" },
  { file: "savta-90-2.webp", caption: "סבתא בת 90 – חלק ב'" },
  { file: "savta-90-3.webp", caption: "סבתא בת 90 – חלק ג'" },
  { file: "savta-95.webp", caption: "סבתא בת 95" },
  { file: "savta-99.webp", caption: "סבתא בת 99" },
  { file: "sukkot-1992.webp", caption: "סוכות, 1992" },
  { file: "skapa-50.webp", caption: "סקפה בן 50" },
  { file: "omri-first-grade-1999.webp", caption: "עמרי עולה לכיתה א', 1999" },
  { file: "omri-second-grade-2000.webp", caption: "עמרי עולה לכיתה ב', 2000" },
  { file: "ein-yahav-25-manuscript.webp", caption: "25 שנה לעין יהב – כתב יד" },
  { file: "ein-yahav-25.webp", caption: "25 שנה לעין יהב" },
  { file: "purim-1968.webp", caption: "פורים, 1968" },
  { file: "purim-1997-1.webp", caption: "פורים 1997 – חלק א'" },
  { file: "purim-1997-2.webp", caption: "פורים 1997 – חלק ב'" },
  { file: "note-to-ruti-jordan-1997.webp", caption: "פתק לרותי בטיול בירדן, קיץ 1997" },
  { file: "cheche-hagi-silver-wedding.webp", caption: "צ'צ'ה וחגי – חתונת הכסף, 1986" },
  { file: "kindergarten-teachers-1970.webp", caption: "ציפי ובת שבע הגננות, יוני 1970" },
  { file: "ktana-chelkat-adam.webp", caption: "\"קטנה חלקת אדם\"" },
  { file: "rosh-hashanah-1981.webp", caption: "ראש השנה, 1981" },
  { file: "rosh-hashanah-1983.webp", caption: "ראש השנה, 1983" },
  { file: "rosh-hashanah-1996.webp", caption: "ראש השנה, 1996" },
  { file: "rosh-hashanah-1997.webp", caption: "ראש השנה, 1997" },
  { file: "ruti-50.webp", caption: "רותי בת 50" },
  { file: "ruti-70-2.webp", caption: "רותי בת 70 – גרסה ב'" },
  { file: "ruti-70.webp", caption: "רותי בת 70" },
  { file: "ruti-60.webp", caption: "רותי בת 60" },
  { file: "reach-hamor-1.webp", caption: "\"ריח המור\" – חלק א'" },
  { file: "reach-hamor-2.webp", caption: "\"ריח המור\" – חלק ב'" },
  { file: "rotem-15.webp", caption: "רתם בת 15" },
  { file: "rotem-15-dudu-south-america.webp", caption: "רתם בת 15 ודודו יוצא לדרום אמריקה" },
  { file: "rotem-18.webp", caption: "רתם בת 18" },
  { file: "rotem-bat-mitzvah-1.webp", caption: "רתם – בת המצווה, חלק א'" },
  { file: "rotem-bat-mitzvah-2.webp", caption: "רתם – בת המצווה, חלק ב'" },
  { file: "rotem-bat-mitzvah-3.webp", caption: "רתם – בת המצווה, חלק ג'" },
  { file: "rotem-kobi-wedding.webp", caption: "רתם וקובי – ליום החתונה" },
  { file: "rotem-kobi-wedding-2.webp", caption: "רתם וקובי – ליום החתונה, גרסה שנייה" },
  { file: "rotem-kobi-roni-2005.webp", caption: "רתם וקובי להולדת רוני, 2005" },
  { file: "rotem-kobi-shahar-2003.webp", caption: "רתם וקובי להולדת שחר, 2003" },
  { file: "rotem-enlistment.webp", caption: "רתם מתגייסת" },
  { file: "rotem-ofer-1998.webp", caption: "רתם להולדת עופר, 1998" },
  { file: "rotem-condolences.webp", caption: "רתם – ניחומים" },
  { file: "rotem-graduation.webp", caption: "רתם מסיימת י\"ב" },
  { file: "sheva-50-1.webp", caption: "שבע בת 50 – חלק א'" },
  { file: "sheva-50-2.webp", caption: "שבע בת 50 – חלק ב'" },
  { file: "sheva-60.webp", caption: "שבע בת 60" },
  { file: "shai-catskills.webp", caption: "שי נוסע לקטסקילס" },
  { file: "shai-63.webp", caption: "שי בן 63" },
  { file: "shai-60.webp", caption: "שי בן 60" },
  { file: "shir-hamichun-1.webp", caption: "\"שיר המיכון\" – חלק א'" },
  { file: "shir-hamichun-2.webp", caption: "\"שיר המיכון\" – חלק ב'" },
  { file: "rosh-hashanah-song-1996.webp", caption: "שיר לראש השנה, 1996" },
  { file: "shchol-1979.webp", caption: "\"שכול\", 1979" },
  { file: "shalom-nosaf.webp", caption: "\"שלום נוסף\"" },
  { file: "aliyah-30-1989.webp", caption: "שלושים שנה לעלייה על הקרקע, 1989" },
  { file: "gad-dan-mishmar-hanegev.webp", caption: "גד ודן – סיום במשמר הנגב" },
  { file: "david-nachmias-1995.webp", caption: "דוד נחמיאס, 1995" },
  { file: "regional-school-1978.webp", caption: "המעבר לבית הספר האזורי, 1978" },
  { file: "zeide-honorary-citizen-1995.webp", caption: "זיידה – אזרח כבוד, 1995" },
  { file: "four-musketeers-1994-1.webp", caption: "לארבעת המוסקטרים, 1994 – חלק א'" },
  { file: "four-musketeers-1994-2.webp", caption: "לארבעת המוסקטרים, 1994 – חלק ב'" },
  { file: "idan-gadish-1997.webp", caption: "לעידן גדיש, 1997" },
  { file: "year-end.webp", caption: "סוף שנה" },
  { file: "oded-ben-menachem.webp", caption: "לעודד בן מנחם בסיום ניהול בית הספר" },
  { file: "kibbutz-galuyot-1980.webp", caption: "\"קיבוץ גלויות\", 1980" },
  { file: "kibbutz-galuyot-1980-manuscript.webp", caption: "\"קיבוץ גלויות\", 1980 – כתב יד" },
  { file: "shalom-1980.webp", caption: "\"שלום\", 1980" },
  { file: "rabin-thanks-1995-1.webp", caption: "שלמי תודה לרבין, 1995 – חלק א'" },
  { file: "rabin-thanks-1995-2.webp", caption: "שלמי תודה לרבין, 1995 – חלק ב'" },
  { file: "grade-12-class-3-1984.webp", caption: "ברכה למסיימי י\"ב מחזור ג', 1984" },
  { file: "haba-koach-manuscript.webp", caption: "\"הבא כוח\" – בכתב ידו של שי" },
  { file: "machar-shai.webp", caption: "\"מחר\" – שירו של שי" }
];
